import Head from "next/head";
import {
	TextContentSection,
	ImageContentSection,
	TextContentWrap,
	TextContentHeading,
	TextContentDescription,
	ImageContentWrap
} from "@/components/about-contents/index";

const About = () => {
	return (
		<>
			<Head>
				<title>About | SmartVA</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<TextContentSection>
				<TextContentWrap>
					<TextContentHeading></TextContentHeading>
					<TextContentDescription></TextContentDescription>
				</TextContentWrap>
			</TextContentSection>
			<ImageContentSection>
				<ImageContentWrap></ImageContentWrap>
			</ImageContentSection>
		</>
	);
};

export default About;
