import Head from "next/head";
import useIsScreenSizes from "@/utils/get-is-screen-sizes";
import {
	ContentContainer,
	InnerContainer,
	GreetingText,
	DescriptionText,
	NameText,
	ImageContainer,
	JumbotronImage,
	SocialMediaContainer
} from "@/layout/home-content";
import { SocialMediaButton } from "@/components/buttons";
import { useThemeCtx } from "@/context/theme";
import BouncingIcon from "@/components/bouncing-icon";
import ThemeDrawer from "@/components/theme-drawer";

export default function Home() {
	const { isMobileXS, isMobileS, isMobileM, isMobileL, isLaptop, isLaptopL, isDesktop } =
		useIsScreenSizes();
	const { isDark } = useThemeCtx();

	const isSmallView = isMobileXS || isMobileS || isMobileM || isMobileL;
	const isBigView = isLaptop || isLaptopL || isDesktop;

	return (
		<>
			<Head>
				<title>Home | SmartVA</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{isBigView ? <ThemeDrawer /> : null}
			<ContentContainer isSmallView={isSmallView}>
				<InnerContainer isSmallView={isSmallView}>
					<GreetingText isSmallView={isSmallView} variant="h1">
						Hello! I&apos;m
					</GreetingText>
					<NameText isDark={isDark} variant="h2">
						Jerome,
					</NameText>
					<DescriptionText isSmallView={isSmallView}>Your Smart Virtual Assistant</DescriptionText>
					<SocialMediaContainer isSmallView={isSmallView}>
						<SocialMediaButton>
							<BouncingIcon code="e92f" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e902" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e934" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e922" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e900" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e930" className="icon" />
						</SocialMediaButton>
					</SocialMediaContainer>
				</InnerContainer>
			</ContentContainer>

			<ImageContainer isSmallView={isSmallView}>
				<JumbotronImage src="/images/jumbotron/jumbotron@1x.png" />
			</ImageContainer>
		</>
	);
}
