import React, { useEffect, useState, useRef } from "react";
import { TimelineMax, TweenLite, gsap, Circ, Power1, Power0 } from "gsap";
import $ from "jquery";
import initBlastText from "@/assets/js/blast";
import Head from "next/head";
import { useIsScreenSizes } from "@/hooks/useIsScreenSizes";
import {
	ContentContainer,
	InnerContainer,
	GreetingText,
	DescriptionText,
	NameText,
	ImageContainer,
	JumbotronImage,
	SocialMediaContainer
} from "@/layout/home-content";
import { SocialMediaButton } from "@/components/buttons";
import { useThemeCtx } from "@/context/theme";
import BouncingIcon from "@/components/bouncing-icon";
import ThemeDrawer from "@/components/theme-drawer";
import { useUiCtx } from "@/context/ui";

const AnimatedJumbotronImage = ({ src, alt }) => {
	const [isAnimated, setIsAnimated] = useState(false);
	const { state: initBounceAnim } = useUiCtx();

	const imageRef = useRef(null);

	useEffect(() => {
		if (initBounceAnim) {
			setTimeout(() => setIsAnimated(true), 10000);
		}
	}, [initBounceAnim]);

	return (
		<JumbotronImage
			ref={imageRef}
			src={src}
			alt={alt}
			className={`animate__animated ${isAnimated ? "animate__bounceInDown show" : ""}`}
		/>
	);
};

export default function Home() {
	const {
		state: { initBlastAnim },
		dispatch: { setInitBounceAnim }
	} = useUiCtx();
	const [initAnimation, setInitAnimation] = useState(false);
	const blastRef = useRef();
	const { isMobileXS, isMobileS, isMobileM, isMobileL, isLaptop, isLaptopL, isDesktop } =
		useIsScreenSizes();
	const { isDark } = useThemeCtx();

	const isSmallView = isMobileXS || isMobileS || isMobileM || isMobileL;
	const isBigView = isLaptop || isLaptopL || isDesktop;

	useEffect(() => {
		const timeout = setTimeout(() => setInitAnimation(true), 8500);

		return () => clearTimeout(timeout);
	}, []);

	useEffect(() => {
		if (initAnimation) {
			initBlastText();
			// Blast.js to split the text into characters
			$(".text-zone h2").blast({ delimiter: "character" });

			// Animate each letter
			$(".text-zone .blast").each(function (index) {
				$(this)
					.css({ opacity: 0, top: "-500px", position: "relative", visibility: "visible" })
					.delay(300 * index)
					.animate(
						{
							top: "0px",
							opacity: 1
						},
						500,
						function () {
							$(this).addClass("animate__animated animate__rubberBand");
							setInitBounceAnim(true);
						}
					);
			});
			// Initial timeout for blast animation
			const blastTimeout = setTimeout(() => {
				$(".text-zone .blast").removeClass("animated bounceIn");
				$(".text-zone .blast").css("opacity", 1);

				$(".text-zone .blast").on("mouseenter", function () {
					const el = $(this);
					el.addClass("animated rubberBand");
					el.one(
						"webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",
						() => {
							el.removeClass("animated rubberBand");
						}
					);
				});
			}, 3000);

			// Cleanup function to remove events and clear timeouts on unmount
			return () => {
				clearTimeout(blastTimeout);
				$(".text-zone .blast").off("mouseenter");
				setInitAnimation(false); // Reset animation state on unmount
			};
		}
	}, [initAnimation]);

	return (
		<>
			<Head>
				<title>Home | SmartVA</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{isBigView ? <ThemeDrawer /> : null}
			<ContentContainer isSmallView={isSmallView}>
				<InnerContainer isSmallView={isSmallView}>
					<GreetingText isSmallView={isSmallView} variant="h1">
						Hello! I&apos;m
					</GreetingText>
					<div className="text-zone">
						<NameText ref={blastRef} variant="h2" isDark={isDark}>
							Jerome,
						</NameText>
					</div>

					<DescriptionText isSmallView={isSmallView}>Your Smart Virtual Assistant</DescriptionText>
					<SocialMediaContainer isSmallView={isSmallView}>
						<SocialMediaButton>
							<BouncingIcon code="e92f" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e902" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e934" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e922" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e900" className="icon" />
						</SocialMediaButton>
						<SocialMediaButton>
							<BouncingIcon code="e930" className="icon" />
						</SocialMediaButton>
					</SocialMediaContainer>
				</InnerContainer>
			</ContentContainer>

			<ImageContainer isSmallView={isSmallView}>
				<AnimatedJumbotronImage src="/images/jumbotron/jumbotron@1x.png" alt="Jumbotron Image" />
			</ImageContainer>
		</>
	);
}
